version: '3.5'

services:
  postgres:
    image: postgres
    env_file:
      - .env # configure postgres
    ports:
      - 5432:5432
    volumes:
      - ./pg-data:/var/lib/postgresql/data/ # persist data even if container shuts down
