version: '3'
services:

  rabbit:
    container_name: dev_rabbit
    hostname: rabbit
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=user
    ports:
      - "5672:5672"
      - "15672:15672"


  redis:
    hostname: redis
    container_name: dev_redis
    image: redis:alpine
    restart: always
    command: [ "redis-server", "--appendonly", "yes" ]

    volumes:
      - ./base_data:/data
      # - ./config:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
